version: 0.1

projects:
  - id: fukukuru-20260718
    keywords:
      - "ふくくるさんぽ"
    scrapbox:
      project: muselab
      page: "ふくくるさんぽ-26/7/18(土)"

  - id: solo-chorus
    keywords:
      - "一人合唱"
      - "一人合唱インタフェース"
    scrapbox:
      project: muselab
      page: "一人合唱インタフェース"

  - id: sigmus147
    keywords:
      - "SIGMUS147"
    scrapbox:
      project: muselab
      page: "SIGMUS147"
